image: node:11.10.1

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test
  - deploy

lint-package:
  stage: build
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn lint

build-package:
  stage: build
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn build

test-package:
  stage: test
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn test
  artifacts:
    name: coverage
    paths:
      - coverage/
    expire_in: 30 days

pages:
  stage: deploy
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn publish:docs
  artifacts:
    paths:
      - public
  only:
    - master
