image: node:11.10.1

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test

lint-package:
  stage: build
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn lint

build-package:
  stage: build
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn build

test-package:
  stage: test
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn test-with-coverage
  artifacts:
    name: coverage
    paths:
      - coverage/
